import { jsPDF } from "jspdf";

// A6 format in milimeters
const pageWidth = 10.5;
const pageHeight = 14.8;

// Utils variable
const margin = 1;
const maxLineWidth = pageWidth - margin * 2;
const maxTextHeight = pageHeight - margin * 2;
const lineHeight = 1.25;
const ptsPerCm = 28.3465;

// font size
const titleFontSize = 22;
const listFontSize = 16;
const footerFontSize = 10;

// footer
const footerText = "Generated by seihoo";

//checkbox
const checkboxSize = 0.5;

const oneLineHeight = (fontSize) => fontSize * lineHeight / ptsPerCm;

const { CheckBox } = jsPDF.AcroForm;

const ingredientMapToString = (map) => {
    let ret = "";

    map.forEach(({ quantity, unit }, name) => {
        ret += `${name.toLowerCase()}    ${quantity} ${unit}\n`;
    })
    return ret;
}

export const generateShoppingList = (ingredientMap) => {
    const doc = new jsPDF({ unit: "cm", format: "a6", lineHeight: lineHeight })
        .setProperties({ title: "Shopping List" });
    const textLines = doc.setFont("helvetica")
        .setFontSize(listFontSize)
        .splitTextToSize(ingredientMapToString(ingredientMap), maxLineWidth);
    let y = margin + oneLineHeight(titleFontSize) * 2;

    textLines.pop(); // remove last \n

    // Write title
    doc.setFont("helvetica", "bold")
        .setFontSize(titleFontSize)
        .text("Shopping List", margin, margin);

    // Write list
    for (const textLine of textLines) {
        let checkbox = new CheckBox();

        checkbox.width = checkboxSize;
        checkbox.height = checkboxSize;
        checkbox.x = margin;
        checkbox.y = y;
        checkbox.color = "green";
        checkbox.appearanceState = "Off";
        checkbox.fontSize = listFontSize;
        doc.addField(checkbox);

        doc.setFont("helvetica", "normal")
            .setFontSize(listFontSize)
            .text(textLine, margin + checkboxSize * 2, y + checkboxSize);

        y += oneLineHeight(listFontSize);
        if (y >= maxTextHeight) {
            doc.addPage();
            y = margin;
        }
    }

    // Write footer
    const footerWidth = doc.getTextWidth(footerText);
    doc
        .setFontSize(footerFontSize)
        .setTextColor("#c0c4cc")
        .text(footerText, margin + (footerWidth / 2), pageHeight - margin);

    // save
    doc.save("list.pdf");
};